db:
  development:
    host: localhost
    database: postgres
    username: postgres
    password: Teratodes66
  production:
    host: ec2-54-243-243-89.compute-1.amazonaws.com
    database: d7bc9b2mvdfj9q
    username: ikjgqxbowiipfw
    password: tdNbQfa5oyKC5EQ71pClxBOKY4
crawlers:
  boligportal:
    base_uri: http://www.boligportal.dk/api/soeg_leje_bolig.php
    regions:
      Nordsjaelland: 2
      Fyn: 3
      Koebenhavn: 4
      Nordjylland: 5
      Sydvestjylland: 6
      Vestjylland: 7
      Roskilde: 8
      Sydsjaelland: 9
      Soenderjylland: 10
      Sydoestjylland: 11
      Vestsjaelland: 12
      Nordvestjylland: 13
      Oestjylland: 14
    types:
      Apartment: 3
      House: 1
      Room: 9
    data: |
      serviceName=getProperties
      &data={
        "amtId":"#{regionId}",
        "huslejeMin":"0",
        "huslejeMax":"50000",
        "stoerrelseMin":"0",
        "stoerrelseMax":"0",
        "postnrArr":[],
        "boligTypeArr":["#{categoryId}"],
        "lejeLaengdeArr":["4"],
        "page":"#{page}",
        "limit":"50",
        "sortCol":"3",
        "sortDesc":"1",
        "visOnSiteBolig":0,
        "almen":-1,
        "billeder":-1,
        "husdyr":-1,
        "mobleret":-1,
        "delevenlig":-1,
        "fritekst":"",
        "overtagdato":"",
        "emailservice":"",
        "kunNyeste":#{only_newest},
        "muListeMuId":"",
        "fremleje":-1,
        "roomsNum":"0"
      }
  dba:
    base_uri: https://api.dba.dk/api/v2/ads/cassearch?cla=#{categoryId}&reg=#{regionId}&at=Udlejes&ot=private&q=&p=0-100000&ps=10&pn=1&format=json
    apiKey: 087157d7-84d5-4f2b-1d02-08d282f6c857
    regions:
      Koebenhavn: 10
      Aarhus: 8000
      Odense: 5000
      Aalborg: 9000
      Jylland: 20
      Nordjylland: 1
      Midt- og Vestjylland: 3
      Sønderjylland: 4
      Fyn: 5
      Sjælland: 2
      Nordsjælland: 6
      Vestsjælland: 7
      Sydsjælland og øer: 8
      Fyn: 5
    types:
      Apartment: 1425
      House: 1610
      Room: 1510
  boligbasen:
    base_uri: http://boligbasen.dk/lejeboliger/omraade/Alle.-1/min-rum/-1/max-leje/-1/postnr-min/#{zip_min}/postnr-max/#{zip_max}
external_services:
  mailgun:
    api_key: 5434aebd8ddc8d84ef64d0b73ed79d3e
    domain_name: sandbox966428d939ad4feea67fedb7c5007a7a
  mailchimp:
    email: fastrent.dk@gmail.com
    username: fastrent
#    password: Teratodfes66&& TODO: I have asked for new password, waiting for email...



